/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-12-25 09:46:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"images/icon.png\"/>\r\n");
      out.write("    <link rel=\"Stylesheet\" href=\"CSS/index-style.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("	<title>E-Commerce HUB</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("	<div class=\"container header\">\r\n");
      out.write("		<div class=\"row title\">\r\n");
      out.write("			<div class=\"col\">\r\n");
      out.write("				<img src=\"images/icon.png\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col\">\r\n");
      out.write("				<h1>E-Commerce HUB</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col\">\r\n");
      out.write("				<ul class=\"navlist\">\r\n");
      out.write("					<li>\r\n");
      out.write("						<a href=\"#home\"><i class='bx bx-home-alt-2'></i>Home</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<a href=\"cart.jsp\"><i class='bx bx-cart-alt'></i>Cart</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<a href=wishlist.jsp><i class='bx bx-heart'></i>Wishlist</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<section id=\"home\">\r\n");
      out.write("    <section class=\"banner\">\r\n");
      out.write("        <div id=\"carouselExampleIndicators\" class=\"carousel slide carousel-fade\" data-bs-ride=\"carousel\" data-bs-interval=\"3000\">\r\n");
      out.write("            <!-- Indicators -->\r\n");
      out.write("            <div class=\"carousel-indicators\">\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Slides -->\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                    <img src=\"images/banner1.jpg\" class=\"d-block w-100\" alt=\"Banner 1\">\r\n");
      out.write("                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                        <h5>Exclusive Deals</h5>\r\n");
      out.write("                        <p>Get the best discounts on top brands</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img src=\"images/banner2.jpg\" class=\"d-block w-100\" alt=\"Banner 2\">\r\n");
      out.write("                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                        <h5>Shop with Confidence</h5>\r\n");
      out.write("                        <p>100% secure shopping experience</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img src=\"images/banner3.jpg\" class=\"d-block w-100\" alt=\"Banner 3\">\r\n");
      out.write("                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                        <h5>Fast Delivery</h5>\r\n");
      out.write("                        <p>Order now and get your items in no time</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Controls -->\r\n");
      out.write("            <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div> \r\n");
      out.write("    </section>  \r\n");
      out.write(" \r\n");
      out.write("    <!-- content -->\r\n");
      out.write("    <section>\r\n");
      out.write("    <div class=\"container content\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <h2>Top Deals</h2>\r\n");
      out.write("            <div class=\"col categories\">\r\n");
      out.write("                <!-- T-Shirt for girls -->\r\n");
      out.write("                <div class=\"items\">\r\n");
      out.write("                    <img src=\"https://images.pexels.com/photos/7432210/pexels-photo-7432210.jpeg?auto=compress&cs=tinysrgb&w=800\" alt=\"T-Shirt for girls\">\r\n");
      out.write("                    <h5>T-Shirt for girls</h5>\r\n");
      out.write("                    <h5>Price: 399/-</h5>\r\n");
      out.write("                    <form action=\"AddToCartServlet\" method=\"POST\" class=\"item-actions\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"product_name\" value=\"T-Shirt for girls\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"price\" value=\"399\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"image_url\" value=\"https://images.pexels.com/photos/7432210/pexels-photo-7432210.jpeg?auto=compress&cs=tinysrgb&w=800\">\r\n");
      out.write("                        <button type=\"submit\" class=\"add\">Add to cart</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <form action=\"AddToWishlistServlet\" method=\"POST\" class=\"wishlist-actions\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"product_name\" value=\"T-Shirt for girls\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"price\" value=\"399\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"image_url\" value=\"https://images.pexels.com/photos/7432210/pexels-photo-7432210.jpeg?auto=compress&cs=tinysrgb&w=800\">\r\n");
      out.write("                        <button type=\"submit\" class=\"wishlist\">\r\n");
      out.write("                            <span>&#9825;</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Womens blazer -->\r\n");
      out.write("                <div class=\"items\">\r\n");
      out.write("                    <img src=\"https://images.pexels.com/photos/19109151/pexels-photo-19109151/free-photo-of-elegant-blazer-on-display.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2\" alt=\"Womens blazer\">\r\n");
      out.write("                    <h5>Womens blazer</h5>\r\n");
      out.write("                    <h5>Price: 1889/-</h5>\r\n");
      out.write("                    <form action=\"AddToCartServlet\" method=\"POST\" class=\"item-actions\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"product_name\" value=\"Womens blazer\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"price\" value=\"1889\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"image_url\" value=\"https://images.pexels.com/photos/19109151/pexels-photo-19109151/free-photo-of-elegant-blazer-on-display.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2\">\r\n");
      out.write("                        <button type=\"submit\" class=\"add\">Add to cart</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <form action=\"AddToWishlistServlet\" method=\"POST\" class=\"wishlist-actions\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"product_name\" value=\"Womens blazer\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"price\" value=\"1889\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"image_url\" value=\"https://images.pexels.com/photos/19109151/pexels-photo-19109151/free-photo-of-elegant-blazer-on-display.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2\">\r\n");
      out.write("                        <button type=\"submit\" class=\"wishlist\">\r\n");
      out.write("                            <span>&#9825;</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Mens blazer -->\r\n");
      out.write("                <div class=\"items\">\r\n");
      out.write("                    <img src=\"https://images.pexels.com/photos/13532890/pexels-photo-13532890.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2\" alt=\"Mens blazer\">\r\n");
      out.write("                    <h5>Mens blazer</h5>\r\n");
      out.write("                    <h5>Price: 1547/-</h5>\r\n");
      out.write("                    <form action=\"AddToCartServlet\" method=\"POST\" class=\"item-actions\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"product_name\" value=\"Mens blazer\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"price\" value=\"1547\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"image_url\" value=\"https://images.pexels.com/photos/13532890/pexels-photo-13532890.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2\">\r\n");
      out.write("                        <button type=\"submit\" class=\"add\">Add to cart</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <form action=\"AddToWishlistServlet\" method=\"POST\" class=\"wishlist-actions\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"product_name\" value=\"Mens blazer\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"price\" value=\"1547\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"image_url\" value=\"https://images.pexels.com/photos/13532890/pexels-photo-13532890.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2\">\r\n");
      out.write("                        <button type=\"submit\" class=\"wishlist\">\r\n");
      out.write("                            <span>&#9825;</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Top -->\r\n");
      out.write("                <div class=\"items\">\r\n");
      out.write("                    <img src=\"https://images.pexels.com/photos/8619007/pexels-photo-8619007.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2\" alt=\"Top\">\r\n");
      out.write("                    <h5>Top</h5>\r\n");
      out.write("                    <h5>Price: 399/-</h5>\r\n");
      out.write("                    <form action=\"AddToCartServlet\" method=\"POST\" class=\"item-actions\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"product_name\" value=\"Top\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"price\" value=\"399\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"image_url\" value=\"https://images.pexels.com/photos/8619007/pexels-photo-8619007.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2\">\r\n");
      out.write("                        <button type=\"submit\" class=\"add\">Add to cart</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <form action=\"AddToWishlistServlet\" method=\"POST\" class=\"wishlist-actions\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"product_name\" value=\"Top\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"price\" value=\"399\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"image_url\" value=\"https://images.pexels.com/photos/8619007/pexels-photo-8619007.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2\">\r\n");
      out.write("                        <button type=\"submit\" class=\"wishlist\">\r\n");
      out.write("                            <span>&#9825;</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Kids T-shirts -->\r\n");
      out.write("                <div class=\"items\">\r\n");
      out.write("                    <img src=\"https://images.pexels.com/photos/26614516/pexels-photo-26614516/free-photo-of-mannequins-of-children-in-clothes.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load\" alt=\"Kids T-shirts\">\r\n");
      out.write("                    <h5>Kids T-shirts</h5>\r\n");
      out.write("                    <h5>Price: 789/-</h5>\r\n");
      out.write("                    <form action=\"AddToCartServlet\" method=\"POST\" class=\"item-actions\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"product_name\" value=\"Kids T-shirts\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"price\" value=\"789\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"image_url\" value=\"https://images.pexels.com/photos/26614516/pexels-photo-26614516/free-photo-of-mannequins-of-children-in-clothes.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load\">\r\n");
      out.write("                        <button type=\"submit\" class=\"add\">Add to cart</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <form action=\"AddToWishlistServlet\" method=\"POST\" class=\"wishlist-actions\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"product_name\" value=\"Kids T-shirts\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"price\" value=\"789\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"image_url\" value=\"https://images.pexels.com/photos/26614516/pexels-photo-26614516/free-photo-of-mannequins-of-children-in-clothes.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load\">\r\n");
      out.write("                        <button type=\"submit\" class=\"wishlist\">\r\n");
      out.write("                            <span>&#9825;</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Unisex T-Shirt -->\r\n");
      out.write("                <div class=\"items\">\r\n");
      out.write("                    <img src=\"https://images.pexels.com/photos/15404590/pexels-photo-15404590/free-photo-of-rack-with-choice-of-sweaters.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2\" alt=\"Unisex T-Shirt\">\r\n");
      out.write("                    <h5>Unisex T-Shirt</h5>\r\n");
      out.write("                    <h5>Price: 799/-</h5>\r\n");
      out.write("                    <form action=\"AddToCartServlet\" method=\"POST\" class=\"item-actions\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"product_name\" value=\"Unisex T-Shirt\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"price\" value=\"799\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"image_url\" value=\"https://images.pexels.com/photos/15404590/pexels-photo-15404590/free-photo-of-rack-with-choice-of-sweaters.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2\">\r\n");
      out.write("                        <button type=\"submit\" class=\"add\">Add to cart</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <form action=\"AddToWishlistServlet\" method=\"POST\" class=\"item-actions wishlist-actions\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"product_name\" value=\"Unisex T-Shirt\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"price\" value=\"799\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"image_url\" value=\"https://images.pexels.com/photos/15404590/pexels-photo-15404590/free-photo-of-rack-with-choice-of-sweaters.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2\">\r\n");
      out.write("                        <button type=\"submit\" class=\"wishlist\">\r\n");
      out.write("                            <span>&#9825;</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<div class=\"col adv\">\r\n");
      out.write("    				<img src=\"images/adv2.jpg\">\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </section>  \r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("	<footer class=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <p>&copy; 2024 E-Commerce HUB. All Rights Reserved.</p>\r\n");
      out.write("                <ul class=\"links\">\r\n");
      out.write("                    <li><a href=\"#\"><i class=\"bx bxl-facebook\"></i>E-Commerce HUB</a></li>\r\n");
      out.write("                    <li><a href=\"#\"><i class=\"bx bxl-twitter\"></i>E-Commerce HUB</a></li>\r\n");
      out.write("                    <li><a href=\"#\"><i class=\"bx bxl-instagram\"></i>E-Commerce HUB</a></li>\r\n");
      out.write("                    <li><a href=\"#\"><i class=\"bx bxl-linkedin\"></i>E-Commerce HUB</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("	\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    window.onload = function() {\r\n");
      out.write("        if(sessionStorage.getItem(\"scrollPos\") != null) {\r\n");
      out.write("            window.scrollTo(0, sessionStorage.getItem(\"scrollPos\"));\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    window.onbeforeunload = function() {\r\n");
      out.write("        sessionStorage.setItem(\"scrollPos\", window.scrollY);\r\n");
      out.write("    };\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
